"""phase 4: AI review columns on analysis_runs, title column on recommendations

Revision ID: 058f531a2511
Revises: 89a4324cf49d
Create Date: 2026-09-02 18:19:40.606525

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '058f531a2511'
down_revision: Union[str, None] = '89a4324cf49d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analysis_runs', sa.Column('ai_summary', sa.Text(), nullable=True))
    op.add_column('analysis_runs', sa.Column('ai_overall_assessment', sa.Text(), nullable=True))
    op.add_column('analysis_runs', sa.Column('ai_improved_code', sa.Text(), nullable=True))
    op.add_column('recommendations', sa.Column('title', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recommendations', 'title')
    op.drop_column('analysis_runs', 'ai_improved_code')
    op.drop_column('analysis_runs', 'ai_overall_assessment')
    op.drop_column('analysis_runs', 'ai_summary')
    # ### end Alembic commands ###
